language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
env:
    - LD_LIBRARY_PATH=$HOME/.locuspocus/lib:$LD_LIBRARY_PATH PATH=$HOME/.locuspocus/bin:$HOME/.locuspocus/conda/bin:$PATH
install:
    - pip install .
script:
    - pip install 'pytest>=3.6' pytest-cov
    - cd tests
    - py.test -v --cov=locuspocus
after_success:
    - coveralls
    - cd ../
deploy:
  provider: pypi
  user: schae234
  password:
    secure: Y+FJUi91IEYBKyRAA6Lp0FNJPph1auEHGK/iAG2Yr0AxkjCWislsqfQScR3MqKUvaie1y3MtXv103jEWczGtn660kVA/wLMvBOcD/BKIUy2fW1+Z3/EKRvYsdAT6wkk4iL/s25In/nRnZxBz8FLIN2UYw3cyNBL8di+cnwi8bpE=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: LinkageIO/LocusPocus
