language: python
python:
  - "3.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors

# Install packages
env:
  - LD_LIBRARY_PATH=$HOME/.locuspocus/lib:$LD_LIBRARY_PATH PATH=$HOME/.locuspocus/bin:$HOME/.locuspocus/conda/bin:$PATH
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n locuspocus python=3 Cython numpy pandas pytest
  - source activate locuspocus
  - python setup.py install
# command to run tests, e.g. python setup.py test
script:  
  - source activate locuspocus
  - py.test tests -v  
